### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by nahara7** [rstudio/rstudio-launcher-plugin-sdk#54]
There are some README updates that can be helpful to share knowledge across teams. Some sections could be:
  -  How to set up the SDK environment both in the development container or locally
  - Connect the different README pages through the main page similar to how is done in the docker repo.
  - Explain how `pull-shared-core.sh` works and how to modify it for new releases

**Comment by kfeinauer** [comment]
We should unify the sub READMEs into the main README here: 
https://github.com/rstudio/rstudio-launcher-plugin-sdk/blob/master/README.md

Ex:
https://github.com/rstudio/rstudio-launcher-plugin-sdk/tree/master/smoke-test
