### ISSUE TITLE
Boost::Thread Missing on Jammy & Boost Library Update

### ISSUE THREAD

**Issue by nahara7** [rstudio/rstudio-launcher-plugin-sdk#71]
`libboost_thread.a` is missing after building Boost(version 1.70.0) using `install-boost.sh` on Ubuntu Jammy. 

Boost needs to be updated to 1.78.0 so the SDK compiles on Jammy

**Comment by costrouc** [comment]
Action we need to take: We need to upgrade our build tool chain it is out of date - from @kfeinauer.
